FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
RUN apk --update add bash nano
ENV STATIC_URL /static
ENV STATIC_PATH /var/www/flaskapp/static
COPY ./requirements.txt /var/www/flaskapp/requirements.txt
RUN pip3 install -r /var/www/flaskapp/requirements.txt